context: You are a helpful assistant.

prompts:
  - key: name
    description: Name of the person
    type: text
    kwargs:
      message: "What's your name?"
      default: Anonymous
      mandatory: true

  - key: favorite_color
    description: Favorite color of the person
    type: radio
    kwargs:
      message: "Choose a color:"
      default: Blue
      mandatory: true
      choices:
        - Red
        - Blue
        - Green

  - key: languages
    type: checkbox
    description: Languages the person knows
    kwargs:
      message: "Select the programming languages you know:"
      choices:
        - Python
        - JavaScript
        - Java
        - C++

  - key: age
    type: range
    description: Age of the person
    kwargs:
      message: "How old are you?"
      min_allowed: 1
      max_allowed: 100

  - key: bio
    type: file
    description: Filepath to a bio about the person
    kwargs:
      message: "Please provide the file path for the bio:"

messages:
  - Show me the information I sent you